### PR TITLE
Map some worldgen stuff

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**

### CODE REVIEW

**Comment by PhoenixVX** [comment]
Nice, but why did you remove some mappings such as Saplings and stuff?

**Comment by amusingimpala75** [comment]
For Ore and Foliage, the mappings were moved from net.minecraft.feature to net.minecraft.world.feature. Since those two mapping were just the class names, it looks like git found it easier to just delete the old one and make a new one. If you look again, you should see a new Ore and Foliage mapping, repackaged

**Comment by BoogieMonster1O1** [comment]
> Nice, but why did you remove some mappings such as Saplings and stuff?

as amusing said, i repackaged them
the `Feature` class was in `n.m.world.feature` but its implementations were in `n.m.feature`
also (partially) matches yarn standards

**Review by sschr15 — APPROVED** [review]

**Review by PhoenixVX — APPROVED** [review]
Looks good as far as I'm concerned.

**Pull request merged**
